name: "Terraform"

on:
  push: 
    branches: ["dev"]
    paths: ["src/**"]
  workflow_dispatch:

jobs: 
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform init
        working-directory: ./src
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"

      - name: Terraform Apply 
        working-directory: ./src
        run: terraform apply --auto-approve